version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.pem:/etc/nginx/localhost.pem
      - ./localhost-key.pem:/etc/nginx/localhost-key.pem
    networks:
      - testing-perf
    links:
      - hello
    ports:
      - "443:443"

  hello:
    image: patrickdappollonio/hello-docker
    networks:
      - testing-perf
    expose:
      - 8000

networks:
  testing-perf:
